### ISSUE TITLE
How to locate evil-fringe-mark in the right side of line numbers

### ISSUE THREAD

**Issue by windrg** [Andrew-William-Smith/evil-fringe-mark#2]
Hi,
I'd like to let it sit on the right side of line numbers like as your screenshot.
Mine is sitting on the left side.
Could I get your some advice, please?

**Comment by choltz** [comment]
It looks like native line numbers are used instead of linum mode. Use this setting in your init file:
```lisp
(global-display-line-numbers-mode)
```

**Comment by windrg** [comment]
Thanks. It works as you told.
