### ISSUE TITLE
working in terminal??

### ISSUE THREAD

**Issue by windrg** [Andrew-William-Smith/evil-fringe-mark#3]
Hi,
I've tried to check whether it works on a terminal mode(--no-window) but it doesn't show anything.
I hope that it would be great for this package to work on a terminal mode as well.

Thanks for this package anyway. 
I was really hating the way evil-visual-mark works which corrupts my holy texts, :-D !!

**Comment by Andrew-William-Smith** [comment]
Thanks for the feedback!  Although terminal Emacs doesn't have a fringe since it can't display graphics, a similar effect can be achieved by placing textual overlays in the margin.  I'm working on an implementation of this feature now in the `develop` branch, which I'll merge with `master` when it's stable.

**Comment by Andrew-William-Smith** [comment]
@windrg Terminal support is nearly complete in the `develop` branch.  Would you mind deleting your current installation and cloning that branch into your `load-path`?  Please let me know if it conforms to your expectations.

To enable Terminal margin display, launch Emacs, run the command `(setq-default left-margin-width 1)`, and open a new buffer.  Place a few marks, and they should appear to the far left of the display.

**Comment by Andrew-William-Smith** [comment]
@windrg Just checking in: have you updated to v1.2.0?  It should display marks in the margin in terminal Emacs if you follow the configuration steps described in the `README`.  Please let me know if the new functionality is to your liking so I can resolve this issue.  Thanks!

**Comment by Andrew-William-Smith** [comment]
Closed for inactivity.
