### ISSUE TITLE
evil-fringe-mark-show-special breaks evil-visual-block

### ISSUE THREAD

**Issue by pjones** [Andrew-William-Smith/evil-fringe-mark#5]
If I enable `evil-fringe-mark-show-special` then `evil-visual-block` selections are all wonky.  It looks like I'm selecting everything from the first column to where point is.  Setting `evil-fringe-mark-show-special` back to `nil` restores `evil-visual-block` to its expected behavior.

  * Evil version 1.2.13
  * `evil-fringe-mark` version 20180619.1534 (MELPA)

**Comment by Andrew-William-Smith** [comment]
Hey, thanks for reporting this issue!  I'm not exactly sure what you're describing; could you post some steps I could take to reproduce the problem?  Thanks!

**Comment by pjones** [comment]
[Here is a video](https://drive.google.com/open?id=1FYEBjxsOHnbBwRDqi8HV_Hrh4mxk2kt4) of what I'm talking about.

It starts off with `evil-fringe-mark-show-special` set to `nil` and I use C-v to start `visual-block-mode`.  Then I set `evil-fringe-mark-show-special` to `t` and use C-v again.

**Comment by Andrew-William-Smith** [comment]
Thank you for the video!  I think this problem may be related to an issue with an older version of `evil-fringe-mark`: the current version, `20180728.647`, involved a rewrite of the marker handling system to fix some common bugs and add support for non-graphical Emacs windows.  I haven't been able to reproduce the issue in your video on that version; would you mind updating and letting me know whether the issue still persists?

**Comment by pjones** [comment]
I upgraded to the latest commit and now I have an error when starting Emacs.  If I `(toggle-debug-on-error)` I see this:

```
Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  marker-position(nil)
  evil-fringe-mark-refresh-visual()
  evil-fringe-mark-refresh-buffer()
  global-evil-fringe-mark-mode()
  run-hooks(evil-mode-hook evil-mode-on-hook)
  #f(compiled-function (&optional arg) (interactive (list (or current-prefix-arg 'toggle))) #<bytecode 0x14f7519>)(nil)
  ad-Advice-evil-mode(#f(compiled-function (&optional arg) (interactive (list (or current-prefix-arg 'toggle))) #<bytecode 0x14f7519>))
  apply(ad-Advice-evil-mode #f(compiled-function (&optional arg) (interactive (list (or current-prefix-arg 'toggle))) #<bytecode 0x14f7519>) nil)
  evil-mode()
```

Which comes from this code:

```elisp
(marker-position evil-visual-end)
```

Since `evil-visual-end` starts out as `nil`.

**Comment by Andrew-William-Smith** [comment]
Oh, I didn't know that commit would close this issue automatically.  I added a short fix for the issue you've described on the latest version; can you confirm that the startup error is now gone?

**Comment by pjones** [comment]
Sorry for the *very long* delay.  This issue is fixed.  Thanks!
